name: bookmap_ver2
description: BookMap Service by Fentarim

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_sign_in: ^6.1.5
  google_nav_bar: ^5.0.6
  http:
  like_button: ^2.0.5
  percent_indicator: ^4.2.3
  cupertino_icons: ^1.0.2
  get: ^4.6.5
  flutter_rating_stars: ^1.0.3+4
  intl: ^0.18.1
  scroll_date_picker: ^3.7.3
  provider:
  flutter_rating_bar:

dev_dependencies:
  flutter_test:
    sdk: flutter
  image_picker: ^1.0.4


  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - src/logo.png
    - src/btn_google_light.png
    - src/sampleBook.jpg
    - src/user_img_default.png

  fonts:
    - family: Roboto
      fonts:
        - asset: src/fonts/Roboto-Medium.ttf
    - family: Pretendard
      fonts:
        - asset: src/fonts/Pretendard-Light.otf
        - asset: src/fonts/Pretendard-Regular.otf
        - asset: src/fonts/Pretendard-SemiBold.otf
    - family: NanumMyeongjo
      fonts:
        - asset: src/fonts/NanumMyeongjo.ttf
        - asset: src/fonts/NanumMyeongjoBold.ttf
        - asset: src/fonts/NanumMyeongjoExtraBold.ttf
